### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by dragonGod97677**
Test PR

### CODE REVIEW

**Comment by dragonGod97677** [comment]
@TheMysticS can you try copying what i modified?
(I did made a correction on oppo app market and added backslash)

**Comment by dragonGod97677** [comment]
If it works, push this to the mystic branch, then to your main and copy it to your PR

**Comment by TheRealMystic** [comment]
SURE.

Is there a space in Oppo's App Market?

Also, there are two instances of system's. You made a change in only one place. Shouldn't it be in both places?

**Comment by dragonGod97677** [comment]
> Is there a space in Oppo's App Market?

Yes

> 
> Also, there are two instances of system's. You made a change in only one place. Shouldn't it be in both places?

Oop, I'll edit it again

**Pull request merged**
